name: qiscus_chat_sdk_example
description: An example for Qiscus Chat SDK
private: true
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  qiscus_chat_sdk:
  flutter:
    sdk: flutter

dependency_overrides:
  qiscus_chat_sdk:
    path: ../
