include: package:pedantic/analysis_options.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
    # always_require_non_null_named_parameters: true
  exclude:
    - 'lib/**/*.g.dart'
    - 'lib/**/*.freezed.dart'
