include: package:pedantic/analysis_options.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
    always_require_non_null_named_parameters: true
    annotate_overrides: ignore
    always_declare_return_types: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - 'lib/**/*.g.dart'
    - 'lib/**/*.freezed.dart'
