include: package:pedantic/analysis_options.yaml

analyzer:
  errors:
    mixin_inherits_from_not_object: ignore
    public_member_api_docs: ignore
    always_require_non_null_named_parameters: true
    annotate_overrides: ignore
    always_declare_return_types: ignore
  exclude:
    - 'example/**'
    - 'lib/**/*.g.dart'
    - 'lib/**/*.freezed.dart'
